apiVersion: apps/v1
kind: Deployment
metadata:
  name: rodrig-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rodrig-app
  template:
    metadata:
      labels:
        app: rodrig-app
    spec:
      containers:
      - name: rodrig-container
        image: rodrigocasio/my-first-k8s-app:v1
        ports:
        - containerPort: 8080
